{
 "title": "mosdns_v5_Shanghai",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", job=\"node\", mode=\"system\"}[$__rate_interval])) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", job=\"node\"}[$__rate_interval]))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", job=\"node\", mode=\"user\"}[$__rate_interval])) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", job=\"node\"}[$__rate_interval]))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", job=\"node\", mode=\"iowait\"}[$__rate_interval])) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", job=\"node\"}[$__rate_interval]))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", job=\"node\", mode=~\"irq\"}[$__rate_interval])) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", job=\"node\"}[$__rate_interval]))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", job=\"node\", mode!~\"user|system|irq|softirq|iowait|idle\"}[$__rate_interval])) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", job=\"node\"}[$__rate_interval]))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", job=\"node\", mode=\"nice\"}[$__rate_interval])) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{instance=\"localhost:9100\", job=\"node\"}[$__rate_interval]))",
     "legendFormat": "Nice"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "网络流量图",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"localhost:9100\", job=\"node\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"localhost:9100\", job=\"node\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Cache hit/query/lazy total ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mosdns_cache_hit_total{instance=\"localhost:9080\"}[$__range]))",
     "legendFormat": "cache hit total"
    },
    {
     "expr": "sum(increase(mosdns_cache_query_total{instance=\"localhost:9080\"}[$__range]))",
     "legendFormat": "cache query total"
    },
    {
     "expr": "sum(increase(mosdns_cache_lazy_hit_total{instance=\"localhost:9080\"}[$__range]))",
     "legendFormat": "cache lazy hit total"
    }
   ]
  },
  {
   "title": "cache 缓存数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "expr": "mosdns_cache_size_current", "legendFormat": "{{tag}}" }
   ]
  },
  {
   "title": "cache 命中率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(mosdns_cache_hit_total[$__rate_interval]) / (increase(mosdns_cache_query_total[$__rate_interval]) != 0)",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "forward 请求",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mosdns_forward_query_total[$__rate_interval])",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "forward 连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "mosdns_forward_conn_opened_total-mosdns_forward_conn_closed_total",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "forward 响应用时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(mosdns_forward_response_latency_millisecond_sum[$__rate_interval]) / (increase(mosdns_forward_response_latency_millisecond_count[$__rate_interval])!=0)",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "forward 新建连接",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(mosdns_forward_conn_opened_total[1m])",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "forward 错误数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "increase(mosdns_forward_err_total[1m])",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "forward 连接复用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "1-(increase(mosdns_forward_conn_opened_total[$__rate_interval])/(increase(mosdns_forward_query_total[$__rate_interval])!=0))",
     "legendFormat": "{{upstream}}"
    }
   ]
  }
 ]
}