{
 "title": "mosdns_V4",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "上游响应用时",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(mosdns_plugin_alidns_met_response_latency_millisecond_sum[$__rate_interval]) / (increase(mosdns_plugin_alidns_met_response_latency_millisecond_count[$__rate_interval]) != 0)",
     "legendFormat": "{{upstream}}Alidns"
    },
    {
     "expr": "increase(mosdns_plugin_dnspod_met_response_latency_millisecond_sum[$__rate_interval]) / (increase(mosdns_plugin_dnspod_met_response_latency_millisecond_count[$__rate_interval]) != 0)",
     "legendFormat": "{{upstream}}Dnspod"
    },
    {
     "expr": "increase(mosdns_plugin_Cloudflare_met_response_latency_millisecond_sum[$__rate_interval]) / (increase(mosdns_plugin_Cloudflare_met_response_latency_millisecond_count[$__rate_interval]) != 0)",
     "legendFormat": "{{upstream}}Cloudflare"
    },
    {
     "expr": "increase(mosdns_plugin_oolongcha_met_response_latency_millisecond_sum[$__rate_interval]) / (increase(mosdns_plugin_oolongcha_met_response_latency_millisecond_count[$__rate_interval]) != 0)",
     "legendFormat": "{{upstream}}Oolongcha"
    },
    {
     "expr": "increase(mosdns_plugin_apad_met_response_latency_millisecond_sum[$__rate_interval]) / (increase(mosdns_plugin_apad_met_response_latency_millisecond_count[$__rate_interval]) != 0)",
     "legendFormat": "{{label_name}}Apad"
    }
   ]
  },
  {
   "title": "Alidns域名查询数量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mosdns_plugin_alidns_met_query_total{job=\"mosdns\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dnspod域名查询数量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mosdns_plugin_dnspod_met_query_total{job=\"mosdns\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oolongcha域名查询数量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mosdns_plugin_oolongcha_met_query_total{job=\"mosdns\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apad域名查询数量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mosdns_plugin_apad_met_query_total{job=\"mosdns\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloudflare域名查询数量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mosdns_plugin_Cloudflare_met_query_total{job=\"mosdns\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS转发请求",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mosdns_plugin_alidns_met_query_total[$__rate_interval])",
     "legendFormat": "{{upstream}}Alidns"
    },
    {
     "expr": "rate(mosdns_plugin_google_met_query_total[$__rate_interval])",
     "legendFormat": "{{upstream}}Google"
    },
    {
     "expr": "rate(mosdns_plugin_dnspod_met_query_total[$__rate_interval])",
     "legendFormat": "{{upstream}}Dnspod"
    },
    {
     "expr": "rate(mosdns_plugin_oolongcha_met_query_total[$__rate_interval])",
     "legendFormat": "{{upstream}}Oolongcha"
    },
    {
     "expr": "rate(mosdns_plugin_apad_met_query_total[$__rate_interval])",
     "legendFormat": "{{label_name}}Apad"
    }
   ]
  },
  {
   "title": "DNS 总响应延迟",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mosdns_plugin_finalmet_response_latency_millisecond_sum{job=\"mosdns\"}[$__range])/increase(mosdns_plugin_finalmet_response_latency_millisecond_count{job=\"mosdns\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS 查询错误率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mosdns_plugin_finalmet_err_total{job=\"mosdns\"}[$__range])/increase(mosdns_plugin_finalmet_query_total{job=\"mosdns\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit/query/lazy total ",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mosdns_plugin_cache_hit_total{instance=\"localhost:9080\"}[$__range]))",
     "legendFormat": "cache hit total"
    },
    {
     "expr": "sum(increase(mosdns_plugin_cache_query_total{instance=\"localhost:9080\"}[$__range]))",
     "legendFormat": "cache query total"
    },
    {
     "expr": "sum(increase(mosdns_plugin_cache_lazy_hit_total{instance=\"localhost:9080\"}[$__range]))",
     "legendFormat": "cache lazy hit total"
    }
   ]
  },
  {
   "title": "DNS 缓存命中率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mosdns_plugin_cache_hit_total[$__rate_interval]) / (increase(mosdns_plugin_cache_query_total[$__rate_interval]) != 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cache 命中率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(mosdns_plugin_cache_hit_total[$__rate_interval]) / (increase(mosdns_plugin_cache_query_total[$__rate_interval]) != 0)",
     "legendFormat": "{{tag}}Mosdns Cache Hit"
    }
   ]
  },
  {
   "title": "cache 缓存数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "targets": [
    { "expr": "mosdns_plugin_cache_cache_size", "legendFormat": "{{tag}}Mosdns Cache Total" }
   ]
  },
  {
   "title": "forward 错误数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(mosdns_plugin_alidns_met_err_total[1m])",
     "legendFormat": "{{upstream}}Alidns"
    },
    {
     "expr": "rate(mosdns_plugin_dnspod_met_err_total[1m])",
     "legendFormat": "{{upstream}}Dnspod"
    },
    {
     "expr": "rate(mosdns_plugin_Cloudflare_met_err_total[1m])",
     "legendFormat": "{{upstream}}Cloudflare"
    },
    {
     "expr": "rate(mosdns_plugin_oolongcha_met_err_total[1m])",
     "legendFormat": "{{upstream}}Oolongcha"
    },
    {
     "expr": "rate(mosdns_plugin_apad_met_err_total[1m])",
     "legendFormat": "{{label_name}}Apad"
    }
   ]
  },
  {
   "title": "DNS 响应延迟热图",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ceil(increase(mosdns_plugin_finalmet_response_latency_millisecond_bucket{le!=\"+Inf\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}